--- #YAML:1.0
name:                AnyEvent-Redis-Federated
version:             0.08
abstract:            Full-featured Async Perl Redis client
license:             ~
author:              
    - jzawodn <jzawodn@craigslist.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    AnyEvent::Redis:               0
    Memory::Usage:                 0
    Set::ConsistentHash:           0
    Test::More:                    0
    Test::TCP:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
